# Generated by Django 4.1.7 on 2023-03-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('result', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
