# Generated by Django 4.1.7 on 2023-04-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_remove_userinput_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinput',
            name='image_type',
            field=models.CharField(choices=[('spiral', 'Spiral'), ('wave', 'Wave')], default='Spiral', max_length=100),
        ),
    ]
